name: Docker Build

on:
  push:
    branches:
      - master
      - dev
      - Arkadiyche1
  pull_request:
    branches: [ master ]

jobs:
  golangci-main:
    name: lint-main
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--config=../.golangci.yml"
          workdir: .